node url join optimized | warehouse privilege grants
FlipsideCrypto/flow-models pull request #144
Opened 2023-08-04 19:22 UTC by ShahNewazKhan

- Updates `network_version` `seed` with `end_height` column for block ranges it covers 
- Renames `aws_flow_api_dev_2` api integration as `aws_flow_api_dev` already exists from prior NBA TS & NFL AD rest api deployments
- Updates network version CTE in base udtf with `end_height` join optimization
- Renames external table to refresh

2023-08-07 15:38 UTC, Ryan-Loofy requested changes

2023-08-07 15:38 UTC, Ryan-Loofy commented on macros/streamline/streamline_udfs.sql
> +        aws_flow_api_dev_2 AS 'https://8jjulyhxhj.execute-api.us-east-1.amazonaws.com/dev/udf_bulk_grpc'
Is there a reason you have 2 here instead of altering the original?

2023-08-07 16:38 UTC, ShahNewazKhan commented on macros/streamline/streamline_udfs.sql
> +        aws_flow_api_dev_2 AS 'https://8jjulyhxhj.execute-api.us-east-1.amazonaws.com/dev/udf_bulk_grpc'
`aws_flow_api_dev_2` was created in june 2022 and used for the `nba ts / nfl ad`  rest api ingestion.

2023-08-15 22:57 UTC, ShahNewazKhan commented
Closing in favor of https://github.com/FlipsideCrypto/flow-models/pull/148

2023-08-15 22:57 UTC, closed without merging