alldaynft metadata with LQ
FlipsideCrypto/flow-models pull request #229
Opened 2023-11-17 19:03 UTC by WHYTEWYLL

2023-11-20 15:44 UTC, desmond-hui requested changes

2023-11-20 15:44 UTC, desmond-hui commented on macros/api_udf/get_allday_metadata.sql
> +            `;
I think this whole part should be a DBT model in the form of a `view`.

2023-11-20 15:44 UTC, desmond-hui commented on macros/api_udf/get_allday_metadata.sql
> +                        livequery_dev.live.udf_api('GET', CONCAT('https://nflallday.com/consumer/graphql?query=','${query}' ), {'Accept-Encoding': 'gzip', 'Content-Type': 'application/json', 'Accept'
`livequery_dev` prefix should be `{{ target.database }}`. We should be updating the `fsc-utils` package to >= 1.11.0 so that we can deploy LiveQuery within the chain databases itself.

2023-11-20 15:44 UTC, desmond-hui commented on macros/api_udf/get_allday_metadata.sql
> +            var counter = snowflake.execute({sqlText: insert_count_command});
Is this for logging purposes only?

2023-11-20 15:44 UTC, desmond-hui commented on macros/api_udf/get_allday_metadata.sql
> +            snowflake.execute({sqlText: insert_command});
IMO remove this insert. Make the data returned by LQ itself a permanently materialized table. AKA change `CREATE OR REPLACE TEMPORARY TABLE {{ target.database }}.bronze_api.response_data` to be the insert statement

2023-11-20 15:44 UTC, desmond-hui commented on macros/api_udf/get_allday_metadata.sql
> +                FROM {{ target.database }}.bronze_api.moments_table
This can likely be a `table(result_scan('<query_id>'))` so that we are hitting cached data, wont have to redo the order by each time

2023-11-20 21:51 UTC, WHYTEWYLL commented on macros/api_udf/get_allday_metadata.sql
> +            var counter = snowflake.execute({sqlText: insert_count_command});
yes

2023-11-21 21:50 UTC, desmond-hui requested changes

2023-11-22 15:44 UTC, desmond-hui requested changes

2023-11-22 15:44 UTC, desmond-hui commented on .github/workflows/dbt_run_moments_metadata.yml
> +        dbt run-operation get_allday_metadata;
Run the `models/silver/nft/livequery/silver__allday_moments_metadata_needed_s.sql` before the stored procedure so that it gets updated to exclude any new data when the table is available

2023-11-27 15:55 UTC, merged